package:
  name: wordcloud
  version: "1.2.1"
  
source:
  git_url: https://github.com/amueller/word_cloud.git
  
requirements:
  build:
    - python

  run:
    - python
    - pillow
    - numpy


test:
  imports:
    - wordcloud

about:
  home: https://github.com/amueller/word_cloud
  license: MIT